name: checkout-code

on : push

jobs :
    checkout-code:
        name: checkout code
        runs-on : ubuntu-latest
        steps :
         -  name : Checkout The Code
            uses : actions/Checkout@v2

         -  name : Run Super Linter
            uses : github/super-linter@v3
            env :
                DEFAULT_BRANCH : main
                GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}